// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQxfBBt6QSl3kMKOWZD_VX_Fo4-lSfQCM',
    appId: '1:424590411878:web:00590d5b9b0f2119e945a7',
    messagingSenderId: '424590411878',
    projectId: 'flutter-88938',
    authDomain: 'flutter-88938.firebaseapp.com',
    storageBucket: 'flutter-88938.firebasestorage.app',
    measurementId: 'G-FBK72VGNQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC9Ui6Y5RFWuYuE7IViXyGxLjYJvB1fBo',
    appId: '1:424590411878:android:630f61e783980f5ae945a7',
    messagingSenderId: '424590411878',
    projectId: 'flutter-88938',
    storageBucket: 'flutter-88938.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT8qk69X3jdLTgSj4ri848lZW46ic_8xw',
    appId: '1:424590411878:ios:19eae105033e0361e945a7',
    messagingSenderId: '424590411878',
    projectId: 'flutter-88938',
    storageBucket: 'flutter-88938.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT8qk69X3jdLTgSj4ri848lZW46ic_8xw',
    appId: '1:424590411878:ios:19eae105033e0361e945a7',
    messagingSenderId: '424590411878',
    projectId: 'flutter-88938',
    storageBucket: 'flutter-88938.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQxfBBt6QSl3kMKOWZD_VX_Fo4-lSfQCM',
    appId: '1:424590411878:web:db6fc8789d4b2390e945a7',
    messagingSenderId: '424590411878',
    projectId: 'flutter-88938',
    authDomain: 'flutter-88938.firebaseapp.com',
    storageBucket: 'flutter-88938.firebasestorage.app',
    measurementId: 'G-V24RK5PPVJ',
  );
}
